### ISSUE TITLE
Per commit deploys

### ISSUE THREAD

**Issue by winny-** [bismuthsoft/super_rogue#11]
Would be pretty cool.

How to get to the deploys including the master branche.

**Comment by winny-** [comment]
If any user can open a PR against this repo, wouldn't that mean anybody can deploy their own website (or malware) on our infrastructure? :exploding_head:

**Comment by 44100hertz** [comment]
> This repo is now public.
> 
> If any user can open a PR against this repo, wouldn't that mean anybody can deploy their own website (or malware) on our infrastructure? exploding_head

@winny- is this still an issue?

**Comment by winny-** [comment]
There's likely no way to achieve this in a secure fashion, except in the case github actions can limit the workflow to organization members.

**Comment by 44100hertz** [comment]
I will close this, then.
